# Generated by Django 4.0 on 2021-12-14 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('followers', '0002_alter_userfollows_follower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfollows',
            name='follower',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='authentication.user'),
        ),
    ]
