# Generated by Django 3.2.9 on 2021-12-04 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0002_alter_ticket_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='headline',
            new_name='title',
        ),
    ]
