# Generated by Django 3.2.9 on 2021-12-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0004_auto_20211204_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='time_created',
            new_name='date_created',
        ),
    ]
