# Generated by Django 3.2.9 on 2021-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flux', '0005_rename_time_created_review_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
